include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/*.g.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart

# https://dart.dev/guides/language/analysis-options
# https://dart-lang.github.io/linter/lints/index.html.
linter:
  rules:
    # Error
    avoid_print: true
    avoid_relative_lib_imports: true
    empty_statements: true
    prefer_single_quotes: true
    # Style
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    always_require_non_null_named_parameters: true
    annotate_overrides: true
    avoid_function_literals_in_foreach_calls: true
    avoid_init_to_null: true
    avoid_positional_boolean_parameters: true
    camel_case_extensions: true
    camel_case_types: true
    cascade_invocations: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: false
    exhaustive_cases: true
    file_names: true
    lines_longer_than_80_chars: true
    prefer_expression_function_bodies: true
    require_trailing_commas: true
    unnecessary_await_in_return: true
